--- #YAML:1.0
name:               App-sipa
version:            0.0001
abstract:           Yet another sip sniffer
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    ExtUtils::Install:    1.46
    ExtUtils::MakeMaker:  6.31
    Module::Build:        0.36
    MooseX::Getopt:       0.31
    MooseX::Traits:       0.11
    MooseX::Types::NetAddr::IP:  0.03
    namespace::autoclean:  0.11
    Net::Pcap::Easy:      1.3
    Test::More:           0.9
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
